config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users,
  controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get 'users/sign_out' =>  'devise/sessions#destroy'
  end
  scope "(:locale)", locale: /en|ru/ do
    resources :users do
      resources :instructions do
        resources :steps
      end
    end
    resources :steps do
      resources :comments
    end
    resources :instructions do
      get :autocomplete_tag_name, :on => :collection
    end
    get 'tags/:tag', to: 'instructions#index', as: "tag"
    root to: 'instructions#index'
    resources :instructions
    resources :steps
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :step
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_step

  def index
    @comments = @step.comments.order('created_at asc')
    respond_to do |format|
      format.html { render layout: !request.xhr? }
    end
  end

  def create
    @comment = @step.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.json { render :show, status: :created, location: @comment }
        format.js
      end
    else
      flash[:alert] = 'Check the comment form, something went wrong.'
      render root_path
    end
  end

  def destroy
    @comment = @step.comments.find(params[:id])
    if @comment.user_id == current_user.id
      @comment.destroy
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_step
    @step = Step.find(params[:step_id])
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
#comment
  .sa
    = comment.user.name
  .span
    = comment.created_at
  = comment.content
  - if comment.user == current_user
    = link_to step_comment_path(@step, comment), method: :delete, data: {step_id: @step.id, value: @step.comments.count, confirm: "Are you sure?" }, remote: true, id: "delete-#{comment.id}", class: "delete-comment" do
      %span(class="glyphicon glyphicon-remove delete-comment-icon")

app/views/comments/create.js.erb
$('#comment_content_<%= @step.id %>').val('')
$('#comment_content_<%= @step.id %>').blur();
Append.comment_count += 1
$(Append.id).attr('data-value', Append.comment_count);

if (Append.comment || Append.open ){ $('#comments_<%= @step.id %>').append("<%=j render 'comments/comment', step: @step, comment: @comment %>"); }

else if ((Append.comment && Append.open) === false && Append.link === true) {
  $('#comments_' + Append.step_id).append("<div class='paginator' id='#comments-paginator-" + Append.step_id + "'><a class='more-comments' id='more_comments_" + Append.step_id + "' data-step-id='" + Append.step_id + "' data-type='html' data-remote='true' data-value='" + Append.comment_count + "' href='/steps/" + Append.step_id + "/comments'>view all " + Append.comment_count + " comments</a></div>");
}

else if ((Append.comment && Append.open && Append.link) === false) { $('#more_comments_<%= @step.id %>').html("view all <%= @step.comments.count %> comments"); }
$('#comments_<%= @step.id %>').html("<%= j render @step.comments, step: @step, comment: @comment %>");

app/views/comments/destroy.js.erb
$('#comments_<%= @step.id %>').html("<%= j render @step.comments, step: @step, comment: @comment %>");
Append.comment_count -= 1

app/views/comments/index.html.haml
= render @comments