config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users,
  controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get 'users/sign_out' =>  'devise/sessions#destroy'
  end
  scope "(:locale)", locale: /en|ru/ do
    resources :users do
      resources :instructions do
        resources :steps
      end
    end
    resources :steps do
      resources :comments
    end
    resources :instructions do
      get :autocomplete_tag_name, :on => :collection
    end
    get 'tags/:tag', to: 'instructions#index', as: "tag"
    root to: 'instructions#index'
    resources :instructions
    resources :steps
  end
end

app/models/step.rb
class Step < ApplicationRecord
  has_many :comments, dependent: :destroy
  belongs_to :instruction
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
  def index
     @steps = Step.where(instruction_id: params[:instruction_id])
     @can_edit = false
     new
  end

  def new
     @step = Step.new
     @photo = Photo.new
  end

  def create
     if parsing_photo(params) != ''
       @photo = save_photo
       return true
     end
     create_step
  end

  def edit
  end

  def update
    if parsing_photo(params) != ''
       @photo = save_photo
       return true
    end
    @step = find_step
    respond_to do |format|
       if @step.update(step_params)
         format.html { render 'steps/#{@step.id}' }
         format.json { render json: @step }
         format.js
       else
         format.html { render :edit }
         format.json { render json: @step.errors, status: :unprocessable_entity }
         format.js { render 'steps/index'}
       end
     end
    photo = Photo.where(user_id: current_user.id, has_connection: false).last
    photo.has_connection = true
    photo.save
  end

  def show
     @can_edit = true
     @step = find_step
  end

  def destroy
    @step = find_step
    if @step.destroy
       respond_to do |format|
         format.html { render steps_path }
         format.json { head :no_content }
         format.js
       end
    end
  end

  private

  def create_step
    instruction_id = parsing_http(request)
    @step = Step.new(instruction_id: instruction_id,
                      description: parsing_description(params),
                      image: choose_photo,
                      user_id: current_user.id)
    respond_to do |format|
      if @step.save
        format.html { redirect_to @step }
        format.json { render :show, status: :created, location: @step }
        format.js
       else
        format.html { render :new }
        format.json { render :json, @step.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

   def choose_photo
      Photo.where(user_id: current_user.id, has_connection: false).last[:image]
   end

   def save_photo
     image = select_image
     @photo = Photo.new(user_id: current_user.id,
                        image: image,
                        has_connection: false)
     @photo.save
   end

  def select_image
    param = params[:photo]
    url = param[:image]
    url[0..param[:image].index('#') - 1]
  end

  def find_step
    @step = Step.find(params[:id])
  end

  def parsing_photo(params)
    @params = params
    @id = @params[:photo]
    return '' if @id == nil
    @id[:image]
  end

  def parsing_description(params)
    text = params[:step]
    text[:description]
  end

  def parsing_http(request)
     @request = save_url(request)
     index = @request.index('=') +  1
     @request = @request[index .. @request.length]
  end

  def save_url(request)
    request.env["HTTP_REFERER"]
  end

  def check_step
    index = save_url(request).index('steps') + 5
    url = save_url(request)
    url[index] == '?' ? true : false
  end

  def step_params
    hash_of_params = {}
    hash_of_params[:description] = parsing_description(params)
    hash_of_params[:image] = Photo.where(user_id: current_user.id,
                                has_connection: false).last.image
    hash_of_params[:user_id] = current_user.id
    hash_of_params
  end
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/steps/_step.html.haml
.stepping-maps
  - if @can_edit
    .col-xs-4.col-sm-4.col-md-12.blog-main.box.text-center{:id => "step_#{step.id}"}
      %h3.panel-title
        = raw(step.description)
      .edit{:"data-toggle" => "modal", :type => "link", :"data-target" => "#myupdatestep_#{step.id}"}
        .panel-heading
          .image-settings
            %img{src: "http://res.cloudinary.com/dtbx6e5eb/#{step.image}",:height => "600em", :width => "600em" }
  - else
    .container.col-sm-11.col-md-3.blog-main.box.text-center{:id => "step_#{step.id}"}
      .panel.panel-info
        %h3.panel-title= raw(step.description)
        .panel-heading
          .image-settings
            = link_to step do
              %img{src: "http://res.cloudinary.com/dtbx6e5eb/#{step.image}", :height => "100%", :width => "100%"  }
      - if user_signed_in?
        - if current_user.id == step.user_id
          .circle
          .delete-icon
            = link_to '', step, method: :delete, class: "glyphicon glyphicon-remove", remote: true
  - if user_signed_in?
    - if current_user.id == step.user_id
      = form_for(step, :method => :put, remote: true) do |f|
        .modal.fade{"aria-labelledby" => "myModalLabel", :id => "myupdatestep_#{step.id}", :role => "dialog", :tabindex => "-1"}
          .modal-dialog
            .modal-content
              .modal-header
                %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :tupe => "button"}
                  %span{"aria-hidden" => "true"} ×
                %h4#myModalLabel.modal-title
                  = t('steps.step.edit-step')
              .modal-body
                .field
                  = t('steps.step.description')
                  = f.cktext_area :description, :class => "form-control"
                  %br/
                #direct_upload.basic-form.dz-clickable.needsclick
                  .dz-message.needsclick.dz-clickable
                    = t('steps.index.dropzone')
                  = hidden_field_tag :direct, params[:direct]
              .modal-footer
                = submit_tag t('steps.step.update-modal'), class: "btn btn-primary"

app/views/steps/_steps.html.haml
= render @steps

app/views/steps/create.js.erb
$("#mynewstep").modal("hide");
$("#container_steps").prepend("<%= j render @step%>");
$("#step_<%= @step.id %>").hide().fadeIn(1000);
$(".form-control").val('');

app/views/steps/destroy.js.erb
$("#step_<%= @step.id %>").fadeOut(600, function(){
  $(this).remove();
});

app/views/steps/index.html.haml
.container
  - if user_signed_in?
    .row
      .text-center
        %button.btn.btn-primary.btn-lg{"data-target" => "#mynewstep", "data-toggle" => "modal", :type => "button"}
          = t('steps.index.new-step')
  .back-up
    %a.btn.btn-warning{:href => "/instructions", :role => "button"}
      =t('steps.index.back-up')
  #container_steps.row
    = render @steps
  = form_for(@step, remote: true, class: 'new_photo needsclick dz-clickable') do |f|
    #mynewstep.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
      .modal-dialog
        .modal-content
          .modal-header
            %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
              %span{"aria-hidden" => "true"}
            %h4#myModalLabel.modal-title
              =t('steps.index.new-step')
          .modal-body
            .field
              = f.label t('steps.index.description')
              = f.cktext_area :description, :class => "form-control"
              #direct_upload.basic-form.dz-clickable.needsclick
                .dz-message.needsclick.dz-clickable
                  = t('steps.index.dropzone')
                = hidden_field_tag :direct, params[:direct]
          .modal-footer
            %button#mynewstepclose.btn.btn-default{"data-dismiss" => "modal", :type => "button"}
              =t('instructions.index.close-modal')
            = submit_tag t('steps.index.new-step'), class: "btn btn-primary"

app/views/steps/show.html.haml
%a.btn.btn-warning{:href => "/steps?instruction_id=#{@step.instruction_id}", :role => "button"}
  =t('steps.index.back-up')

= render 'step', step: @step
.container.col-sm-11
  .comments{id: "comments_#{@step.id}"}
    -if @step.comments.any?
      = render @step.comments.first(4), step: @step
      -unless @step.comments.count <= 4
        .paginator{id: "#comments-paginator-#{@step.id}"}
          =link_to "view all #{@step.comments.count} comments", step_comments_path(@step), remote: true, class: 'more-comments', id: "more_comments_#{@step.id}", data: {step_id: "#{@step.id}", type: "html", value: "#{@step.comments.count}"}
.comment-form.col-sm-11
  =form_for([@step, @step.comments.build], remote: true) do |f|
    - if user_signed_in?
      =f.text_field :content, placeholder:  t('steps.show.comment'),
                               class: "comment_content",
                               id: "comment_content_#{@step.id}",
                               data: { step_id: "#{@step.id}",
                               value: "#{@step.comments.count}" }
      =f.submit 'New Comment', class: 'comment-submit-button'

app/views/steps/update.js.erb
$("#myupdatestep_<%= @step.id %>").modal('hide');
$("#step_<%= @step.id %>").fadeOut(400, function(){
  $(this).remove();
  $("#container_steps").prepend("<%= j render @step %>");
});ste