config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users,
  controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  devise_scope :user do
    get 'users/sign_out' =>  'devise/sessions#destroy'
  end
  scope "(:locale)", locale: /en|ru/ do
    resources :users do
      resources :instructions do
        resources :steps
      end
    end
    resources :steps do
      resources :comments
    end
    resources :instructions do
      get :autocomplete_tag_name, :on => :collection
    end
    get 'tags/:tag', to: 'instructions#index', as: "tag"
    root to: 'instructions#index'
    resources :instructions
    resources :steps
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title CourseProject
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css", :rel => "stylesheet"}/
    = javascript_include_tag Ckeditor.cdn_url
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag 'favicon.ico'

  %body
    %nav.navbar.navbar-default
      .container-fluid
        .navbar-header
          %a.navbar-brand{href: '/'}
            = t('layouts.application.brand')
          %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
          %br
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          .language-switcher
            %a.navbar-brand{:href => root_path(locale: :en)} en
            %a.navbar-brand{:href => root_path(locale: :ru)} ru
          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li
                .container-nickname
                  = current_user.name
              %li= link_to t('layouts.application.sign-out'), users_sign_out_path, method: :delete
            - else
              .dropdown
                %button#dropdownMenu1.btn.btn-default.dropdown-toggle{"aria-expanded" => "true", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
                  = t('layouts.application.social-login')
                  %span.caret
                %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu1"}
                  %li
                    = link_to user_twitter_omniauth_authorize_path do
                      .fa.fa-twitter
                      Twitter
                  %li
                    = link_to user_facebook_omniauth_authorize_path do
                      .fa.fa-facebook
                      Facebook
                  %li
                    = link_to user_vkontakte_omniauth_authorize_path do
                      .fa.fa-vk
                      VK
  .container
    - flash.each do |key, value|
      %div{:class => "alert alert-#{key}"}
        = value
    = yield